picture_mapper/picture_app/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from .views import UploadPictureView, EditPictureView, PictureAjaxView, DeletePictureView

urlpatterns = patterns('',
    # Picture model urls
    url(r'^upload/$', login_required(UploadPictureView.as_view()), name='upload_picture'),
    url(r'^edit/(?P<pk>\d+)/$', login_required(EditPictureView.as_view()), name='edit_picture'),
    url(r'^delete/(?P<pk>\d+)/$', login_required(DeletePictureView.as_view()), name='delete_picture'),

    # Global map url
    url(r'^map/$', login_required(TemplateView.as_view(template_name='show_map.html')), name="map"),

    # Picture data AJAX url
    url(r'^map/picture-data/$', login_required(PictureAjaxView.as_view()), name="picture_data"),

)

picture_mapper/picture_mapper/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView, ListView
from django.contrib.auth.decorators import login_required
from core.views import RedirectRegistrationView
from picture_app.views import ProfileView
from picture_app.models import Picture

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', ListView.as_view(template_name='home.html',
                                queryset=Picture.objects.all().order_by('-created')[:10]), name="home"),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # django-registration urls
    url(r'^register/$', RedirectRegistrationView.as_view(), name='registration_register'),
    url(r'^register/closed/$',
        TemplateView.as_view(template_name='registration/registration_closed.html'),
        name='registration_disallowed'),
    (r'^accounts/', include('registration.auth_urls')),
    url(r'^accounts/profile/', login_required(ProfileView.as_view()), name="profile"),

    # picture app urls
    (r'^pictures/', include('picture_app.urls')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

picture_mapper/core/models.py
from django.db import models
from django.contrib.auth.models import User


class CreateTimeStampedModel(models.Model):
    """
    An abstract base class model that provides selfupdating ``created`` and ``modified`` fields,
    and an author field that records the user that created the model instance
    """
    author = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class GetUniqueOrNoneManager(models.Manager):
    """Adds get_unique_or_none method to objects"""
    def get_unique_or_none(self, **kwargs):
        try:
            return self.get(**kwargs)
        except (self.model.DoesNotExist, self.model.MultipleObjectsReturned):
            return None

picture_mapper/picture_app/models.py
from decimal import Decimal
from django.db import models
from django.core.exceptions import ValidationError
from core.models import CreateTimeStampedModel, GetUniqueOrNoneManager


def latitude_validator(value):
    if not Decimal('-90') <= value <= Decimal('90'):
        raise ValidationError(u'%s not a valid latitude.' % value)


def longitude_validator(value):
    if not Decimal('-180') <= value <= Decimal('180'):
        raise ValidationError(u'%s not a valid longitude.' % value)


class Picture(CreateTimeStampedModel):
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=1024, null=True, blank=True)
    height = models.PositiveIntegerField()
    width = models.PositiveIntegerField()
    image = models.ImageField(upload_to="users/images/", height_field='height', width_field='width')
    latitude = models.DecimalField(max_digits=10, decimal_places=8, validators=[latitude_validator])
    longitude = models.DecimalField(max_digits=11, decimal_places=8, validators=[longitude_validator])

    objects = GetUniqueOrNoneManager()

    def __unicode__(self):
        return self.title

    class Meta:
        db_table = 'picture'

picture_mapper/core/forms.py
from django import forms


class AuthorModelForm(forms.ModelForm):
    """
    Custom ModelForm that automatically adds the currently
    logged in user as the author of the model record
    """
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        return super(AuthorModelForm, self).__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        kwargs['commit'] = False
        obj = super(AuthorModelForm, self).save(*args, **kwargs)
        if self.request:
            obj.author = self.request.user
        obj.save()
        return obj

picture_mapper/picture_app/forms.py
from django import forms
from .models import Picture
from core.forms import AuthorModelForm


class PictureForm(AuthorModelForm):
    title = forms.CharField(max_length=255)
    description = forms.Textarea()

    class Meta:
        model = Picture
        exclude = ('author', 'width', 'height',)

picture_mapper/core/views.py
from registration.backends.simple.views import RegistrationView


class RedirectRegistrationView(RegistrationView):
    """
    Subclassing django-registration RegistrationView so
    that it re-directs to the user's profile page after
    successful registration.
    """
    def get_success_url(self, request, user):
        return "/accounts/profile/"

picture_mapper/picture_app/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, View, ListView, UpdateView, DeleteView
from braces.views import FormMessagesMixin, JSONResponseMixin
from .forms import PictureForm
from .models import Picture


class ProfileView(ListView):
    template_name = 'profile.html'
    queryset = Picture.objects.all()

    def get_queryset(self):
        return self.request.user.picture_set.all()


class PictureViewMixin(FormMessagesMixin):
    model = Picture
    template_name = 'forms/picture_form.html'
    form_class = PictureForm
    success_url = reverse_lazy('profile')

    def get_form_kwargs(self):
        """
        Returns the keyword arguments for instanciating the form.
        Need this to replace request kwarg (AuthorForm popped it)
        """
        kwargs = {
            'initial': self.get_initial(),
            'instance': self.object}
        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
                'request': self.request})
        return kwargs


class UploadPictureView(PictureViewMixin, CreateView):

    def get_form_invalid_message(self):
        return 'Failed to save {0}'.format(self.model._meta.verbose_name)

    def get_form_valid_message(self):
        return '{0} uploaded'.format(self.object.title)


class EditPictureView(PictureViewMixin, UpdateView):

    def get_queryset(self):
        # Make sure user can only edit their own pictures
        return self.request.user.picture_set.all()

    def get_form_invalid_message(self):
        return 'Failed to save {0}'.format(self.model._meta.verbose_name)

    def get_form_valid_message(self):
        return '{0} updated'.format(self.object.title)


class DeletePictureView(DeleteView):
    template_name = None
    success_url = reverse_lazy('profile')
    model = Picture

    def get_queryset(self):
        # Make sure user can only delete their own pictures
        return self.request.user.picture_set.all()


class PictureAjaxView(JSONResponseMixin, View):
    content_type = 'application/json'

    def get_queryset(self):
        queryset = Picture.objects.all() \
                          .values('title', 'image', 'author__username',
                                  'created', 'description', 'latitude', 'longitude',)
        # If the request has "user" parameter we want to filter the queryset on the user id
        if "user" in self.request.GET:
            return list(queryset.filter(author=self.request.GET["user"]))
        else:
            return list(queryset)

    def get(self, request, *args, **kwargs):
        # JSON serialize the queryset
        context_dict = {
            'pictures': self.get_queryset(),
        }
        return self.render_json_response(context_dict)

picture_mapper/picture_app/templates/all_markers.html
{% extends 'easy_maps/map.html' %}
{% load staticfiles %}

{% block map_js %}
    <script src="{% static 'js/googlemaps.js' %}"></script>
    {{ block.super }}
{% endblock %}

{% block extra_js %}
            $.get('{% url 'picture_data' %}', function(data) {
                map.getPictureDataFromJson(data);
            });
{% endblock %}

picture_mapper/picture_app/templates/forms/picture_form.html
{% extends "form_base.html" %}
{% load easy_maps_tags %}
{% load staticfiles %}

{% block title %}Upload Picture{% endblock %}
{% block header %}Upload a Picture{% endblock %}
{% block form_url %}{% url 'upload_picture' %}{% endblock %}
{% block submit_text %}Upload{% endblock %}

{% block content %}
<div class="alert alert-block">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <h4>Hint:</h4>
    <p>If your image location details aren't automatically filled in, right-click the
       map at the location you took the picture. The coordinates will be added for you!</p>
</div>
{{ block.super }}
{% endblock %}

{% block row_content %}
{{ block.super }}
<div class="span5 offset1">
    <h1>Location Picker</h1>
    {% easy_map None 450 350 5 using 'location_picker.html' %}
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'js/jpegmeta.js' %}"></script>
{% endblock extra_js %}

picture_mapper/picture_app/templates/location_picker.html
{% extends 'easy_maps/map.html' %}
{% load staticfiles %}

{% block map_js %}
    <script src="{% static 'js/googlemaps.js' %}"></script>
    {{ block.super }}
{% endblock %}

{% block extra_js %}
            var latField = $('#id_latitude');
            var lngField = $('#id_longitude');
            var imgField = $('#id_image');
            map.locationPicker(latField, lngField);
            getLatLngFromExif(latField, lngField, imgField, map)
{% endblock %}

picture_mapper/picture_app/templates/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load easy_maps_tags %}
{% load staticfiles %}

{% block title %}Profile{% endblock %}
{% block content %}
<div class="row">
    <div class="span12">
        <h1>{% block header %}{{ user.username }}'s Profile{% endblock %}</h1>
    </div>
    <div class="span12">
        <a data-toggle="collapse" data-target="#map-section" class="btn btn-info btn-large">Toggle Map</a>
        <a class="btn btn-primary btn-large" href="{% url 'upload_picture' %}">Upload a Picture!</a>
    </div>
    <div id="map-section" class="span12 collapse out">
        <div class="page-header">
            <h3>Map View</h3>
        </div>
        {% easy_map None 940 600 3 using 'user_markers.html' %}
    </div>
    <div class="span12">
        <div class="page-header">
            <h3>Your Pictures</h3>
        </div>
    </div>
    <div class="span12">
        <ul class="thumbnails">
            {% for picture in picture_list %}
            <div id="lightbox_{{ picture.pk }}" class="lightbox hide fade"  tabindex="-1" role="dialog" aria-hidden="true">
                <div class='lightbox-content'>
                    <img src="{{ picture.image.url }}">
                    <div class="lightbox-caption">
                        <h4>{{ picture.title }}</h4>
                        <p>{{ picture.description }}</p>
                    </div>
                </div>
            </div>
            <li>
                <a data-toggle="lightbox" href="#lightbox_{{ picture.pk }}">
                    <div class="thumbnail">
                        <img class="thumbnail-image" src="{{ picture.image.url }}" alt="">
                        <div class="btn-ctrl">
                            <a class="btn btn-thumb btn-primary" href="{% url 'edit_picture' picture.pk %}">Edit</a>
                            <a class="btn btn-thumb btn-danger" onclick="deleteModel('{% url 'delete_picture' picture.pk %}')">Delete</a>
                        </div>
                    </div>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'js/csrf.js' %}"></script>
{% endblock %}

picture_mapper/picture_app/templates/show_map.html
{% extends "base.html" %}
{% load easy_maps_tags %}

{% block title %}Global Picture Map{% endblock %}

{% block content %}

{% easy_map None 940 600 3 using 'all_markers.html' %}

{% endblock %}

picture_mapper/picture_app/templates/user_markers.html
{% extends 'easy_maps/map.html' %}
{% load staticfiles %}

{% block map_js %}
    <script src="{% static 'js/googlemaps.js' %}"></script>
    {{ block.super }}
{% endblock %}

{% block extra_js %}
            $.get('{% url 'picture_data' %}',{'user': '{{ request.user.id }}'}, function(data) {
                map.getPictureDataFromJson(data);
            });
{% endblock %}

picture_mapper/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Picture Mapper{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    {% block extra_meta %}{% endblock %}

    <!-- The styles -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="{% static 'css/bootstrap-responsive.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-lightbox.min.css' %}" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
     <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    <!-- Use this to quickly test CSS changes in a template,
        then move to project.css -->
    {% block extra_css %}{% endblock extra_css %}
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="{% url 'home' %}">Picture Mapper</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              {% if user.is_authenticated %}
              <li><a href="{% url 'map' %}">View Map</a></li>
              <li><a href="{% url 'profile' %}">My Profile</a></li>
              <li><a href="{% url 'auth_logout' %}">Logout</a></li>
              {% else %}
              <li><a href="{% url 'auth_login' %}">Login</a></li>
              <li><a href="{% url 'registration_register' %}">Register</a></li>
              {% endif %}
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    {% comment %}
    <!--
      Takes any django message instances in the http response and
      displays them with appropriate styling.
    -->
	{% endcomment %}

    {% for message in messages %}
    <div class="alert {% if message.tags %}{{ message.tags }}{% endif %}">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>{{ message }}!</strong>
    </div>
    {% endfor %}

    <div id="main" class="container">

      {% block content %}
      {% endblock content %}

    </div> <!-- /container -->

    <!-- The javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-lightbox.min.js' %}"></script>

    <!-- place project specific Javascript in this file -->
    <script src="{% static 'js/project.js' %}"></script>

    {% block extra_js %}
    {% endblock extra_js %}
  </body>
</html>

picture_mapper/templates/core/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load easy_maps_tags %}
{% load staticfiles %}

{% block title %}Profile{% endblock %}
{% block content %}
<div class="row">
    <div class="span12">
        <h1>{% block header %}{{ user.username }}'s Profile{% endblock %}</h1>
    </div>
    <div class="span12">
        <div class="page-header">
            <h3>Your Pictures</h3>
        </div>
    </div>
    <div class="span12">
        <ul class="thumbnails">
            {% for picture in picture_list %}
            <div id="lightbox_{{ picture.pk }}" class="lightbox hide fade"  tabindex="-1" role="dialog" aria-hidden="true">
                <div class='lightbox-content'>
                    <img src="{{ picture.image.url }}">
                    <div class="lightbox-caption">
                        <h4>{{ picture.title }}</h4>
                        <p>{{ picture.description }}</p>
                    </div>
                </div>
            </div>
            <li>
                <a data-toggle="lightbox" href="#lightbox_{{ picture.pk }}">
                    <div class="thumbnail">
                        <img class="thumbnail-image" src="{{ picture.image.url }}" alt="">
                        <div class="btn-ctrl">
                            <a class="btn btn-thumb btn-primary" href="{% url 'edit_picture' picture.pk %}">Edit</a>
                            <a class="btn btn-thumb btn-danger" onclick="deleteModel('{% url 'delete_picture' picture.pk %}')">Delete</a>
                        </div>
                    </div>
                </a>
            </li>
            {% endfor %}
        </ul>
        <a class="btn btn-primary btn-large" href="{% url 'upload_picture' %}">Upload a Picture!</a>
    </div>
    <div class="span12">
        <div class="page-header">
            <h3>Map View</h3>
        </div>
    </div>
    <div class="span12">
        {% easy_map None 940 600 3 using 'picture_app/user_markers.html' %}
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'js/csrf.js' %}"></script>
{% endblock %}

picture_mapper/templates/form_base.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Base Form Template{% endblock %}

{% block content %}
<div class="row">
    {% block row_content %}
    <div class="span6">
        <h1>{% block header %}Base Form Template{% endblock %}</h1>
        <form class="form-horizontal" method="post" enctype="multipart/form-data" action="">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="control-group">
              <div class="controls">
                <button type="submit" class="btn">{% block submit_text %}{% endblock %}</button>
              </div>
            </div>
        </form>
    </div>
    {% endblock %}
</div>
{% endblock %}

picture_mapper/templates/home.html
{% extends "base.html" %}

{% block title %}Picture Mapper{% endblock %}

{% block content %}
<div class="row">
    <div class="span12">
        <h1>Welcome {% if request.user.is_authenticated %}back {{ user.username }}! {% else %}to Picture Mapper!{% endif %}</h1>
    </div>
    {% if request.user.is_authenticated %}
    <div class="span12">
        <a class="btn btn-large btn-info" href="{% url 'profile' %}">Visit Your Profile</a>
        <a class="btn btn-large btn-info" href="{% url 'map' %}">View Live Map</a>
        <h3>Recent Uploads</h3>
        <ul class="thumbnails">
            {% for picture in picture_list %}
            <div id="lightbox_{{ picture.pk }}" class="lightbox hide fade"  tabindex="-1" role="dialog" aria-hidden="true">
                <div class='lightbox-content'>
                    <img src="{{ picture.image.url }}">
                    <div class="lightbox-caption">
                        <h4>{{ picture.title }} - Uploaded by {{ picture.author.username }}</h4>
                        <p>{{ picture.description }}</p>
                    </div>
                </div>
            </div>
            <li>
                <a data-toggle="lightbox" href="#lightbox_{{ picture.pk }}">
                    <div class="thumbnail">
                        <img class="thumbnail-image" src="{{ picture.image.url }}" alt="">
                    </div>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
    {% else %}
    <div class="span6">
        <img class="image-shadow" src="{{ STATIC_URL }}img/homepage-map.png"/>
        <p class="home-page">
            Picture Mapper allows you to upload your pictures from around the world and pin them on a global map!
            Your pictures will then be viewable by other users, showing them exactly where you took your amazing photos!
            Now is the perfect time to show off, click Register to signup or Login if you are already a member.
        </p>
        <a class="btn btn-large btn-primary" href="{% url 'auth_login' %}">Login</a>
        <a class="btn btn-large btn-success" href="{% url 'registration_register' %}">Register</a>
    </div>
    {% endif %}
</div>
{% endblock %}

picture_mapper/templates/picture_app/forms/picture_form.html
{% extends "form_base.html" %}
{% load easy_maps_tags %}

{% block title %}Upload Picture{% endblock %}
{% block header %}Upload a Picture{% endblock %}
{% block form_url %}{% url 'upload_picture' %}{% endblock %}
{% block submit_text %}Upload{% endblock %}

{% block content %}
<div class="alert alert-block">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <h4>Hint:</h4>
    <p>Right-click the map at the location you took the picture. The coordinates will be added for you!</p>
</div>
{{ block.super }}
{% endblock %}

{% block row_content %}
{{ block.super }}
<div class="span5 offset1">
    <h1>Location Picker</h1>
    {% easy_map None 450 350 5 using 'picture_app/location_picker.html' %}

</div>
{% endblock %}

picture_mapper/templates/picture_app/map_with_markers.html
{% extends 'easy_maps/map.html' %}

{% block extra_js %}
            $.get('{% url 'picture_data' %}', function(data) {
                map.getPictureDataFromJson(data);
            });
{% endblock %}

picture_mapper/templates/picture_app/show_map.html
{% extends "base.html" %}
{% load easy_maps_tags %}

{% block title %}Global Picture Map{% endblock %}

{% block content %}

{% easy_map None 940 600 3 using 'picture_app/all_markers.html' %}

{% endblock %}